/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/batch/csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Match Csv Batch
     * @description Validate two CSVs and return all recommendations and company details in one response.
     */
    post: operations["match_csv_batch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batch/simulate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Simulate Batch Recommendations
     * @description The background robot for one day: newly published notices, suppliers to invite for each
     *     (known ones with the reason, plus new companies from the SME registry).
     */
    post: operations["simulate_batch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrichment/{inn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Enrichment
     * @description Company card: bidding history from the data plus OKVED, role and size from the SME
     *     registry. Works for new companies that never bid too.
     */
    get: operations["get_enrichment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description The API is up; engine: idle / loading / ready / failed (search needs ready).
     */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lots/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Lots
     * @description Find lots by subject text, lot id or registry number; newest first.
     */
    get: operations["search_lots"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lots/{lot_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lot
     * @description A lot with its items, OKPD2 codes and the real winners.
     */
    get: operations["get_lot"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/suppliers/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Search Suppliers
     * @description Rank suppliers for a lot from the data (lot_id) or a new one (lot), with explanations,
     *     plus new companies from the SME registry that fit the lot.
     */
    post: operations["search_suppliers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BatchLotResult */
    BatchLotResult: {
      /**
       * Actual Winners
       * @description Who really won (demo)
       */
      actual_winners: string[];
      /** Invitations */
      invitations: components["schemas"]["Invitation"][];
      lot: components["schemas"]["LotListItem"];
      /**
       * Winner Invited
       * @description The real winner is among the invitations (demo)
       */
      winner_invited: boolean;
    };
    /** BatchResponse */
    BatchResponse: {
      /**
       * Day
       * Format: date
       * @description Publication date of the processed notices
       */
      day: string;
      /** Lots */
      lots: components["schemas"]["BatchLotResult"][];
      /** Timing Ms */
      timing_ms: number;
      /** Total Invitations */
      total_invitations: number;
    };
    /** Body_match_csv_batch */
    Body_match_csv_batch: {
      /**
       * Items
       * Format: binary
       * @description Raw product items CSV
       */
      items: string;
      /**
       * Notices
       * Format: binary
       * @description Raw notices CSV
       */
      notices: string;
    };
    /**
     * CompanyTrust
     * @description Open FNS data: accounting statements, taxes, EGRUL.
     */
    CompanyTrust: {
      /**
       * Expenses
       * @description Expenses for the last year, RUB
       */
      expenses: number | null;
      /** Headcount */
      headcount: number | null;
      /** Registered */
      registered: string | null;
      /**
       * Revenue
       * @description Income for the last year, RUB
       */
      revenue: number | null;
      /**
       * Status
       * @description ACTIVE, INACTIVE, LIQUIDATION_STAGE, ... from the statements registry
       */
      status: string | null;
      /**
       * Tax Debt
       * @description Tax arrears, penalties and fines, RUB
       */
      tax_debt: number | null;
      /**
       * Taxes Paid
       * @description Taxes and contributions paid, RUB
       */
      taxes_paid: number | null;
      /** Warnings */
      warnings: string[];
    };
    /** CsvBatchErrorResponse */
    CsvBatchErrorResponse: {
      /** Detail */
      detail: string | components["schemas"]["ValidationIssue"][];
    };
    /** CsvBatchResponse */
    CsvBatchResponse: {
      /** Lots */
      lots: components["schemas"]["SearchResponse"][];
      /**
       * Selection Policy
       * @description Human-readable automatic selection rule
       */
      selection_policy: string;
      /** Supplier Cards */
      supplier_cards: {
        [key: string]: components["schemas"]["SupplierCard"] | null;
      };
      /** Timing Ms */
      timing_ms: number;
      /** Total Items */
      total_items: number;
      /** Total Lots */
      total_lots: number;
      /** Total Recommendations */
      total_recommendations: number;
    };
    /**
     * EvidenceLot
     * @description A past lot similar to the query that the supplier bid on.
     */
    EvidenceLot: {
      /** Lot Id */
      lot_id: number;
      /** Publish Date */
      publish_date: string | null;
      /** Start Price */
      start_price: number | null;
      /** Subject */
      subject: string | null;
      /** Won */
      won: boolean;
    };
    /** Explanation */
    Explanation: {
      /** Evidence */
      evidence: components["schemas"]["EvidenceLot"][];
      /** Factors */
      factors: components["schemas"]["XaiFactor"][];
      /**
       * Level
       * @enum {string}
       */
      level: "HIGH" | "MEDIUM" | "LOW";
      /** Summary */
      summary: string;
    };
    /** HealthResponse */
    HealthResponse: {
      /** Engine */
      engine: string;
      /**
       * Service
       * @constant
       */
      service: "rlthack-recsys-backend";
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /**
     * Invitation
     * @description A supplier the robot would invite to the lot's procurement.
     */
    Invitation: {
      /** Inn */
      inn: string;
      /**
       * Is New
       * @description From the SME registry, never bid before
       */
      is_new: boolean;
      /** Name */
      name: string | null;
      /** Reason */
      reason: string;
      /** Role Display */
      role_display: string;
      /** Score */
      score: number;
    };
    /** LotCard */
    LotCard: {
      /**
       * Actual Winners
       * @description INNs of the real winners, for lots from the data (demo)
       */
      actual_winners: string[];
      /** Channel */
      channel: string | null;
      /** Customer Inn */
      customer_inn: string | null;
      /** Is Smp */
      is_smp: boolean;
      /** Items */
      items: string[];
      /**
       * Lot Id
       * @description None for a new lot
       */
      lot_id: number | null;
      /** Okpd2 Codes */
      okpd2_codes: string[];
      /** Procedure Name */
      procedure_name: string | null;
      /** Publish Date */
      publish_date: string | null;
      /** Start Price */
      start_price: number | null;
      /** Subject */
      subject: string;
    };
    /** LotListItem */
    LotListItem: {
      /** Channel */
      channel: string | null;
      /** Customer Inn */
      customer_inn: string | null;
      /** Lot Id */
      lot_id: number;
      /** Publish Date */
      publish_date: string | null;
      /** Start Price */
      start_price: number | null;
      /** Subject */
      subject: string | null;
    };
    /**
     * NewLot
     * @description A procurement that is not in the data yet, typed in by the user.
     */
    NewLot: {
      /**
       * Channel
       * @description «АИС ГЗ» or «ЭМ» (e-shop)
       */
      channel: string | null;
      /** Customer Inn */
      customer_inn: string | null;
      /**
       * Is Smp
       * @description Only for SMEs
       */
      is_smp: boolean;
      /**
       * Items
       * @description Item (TRU) names
       */
      items: string[];
      /**
       * Okpd2 Codes
       * @example [
       *       "20.59.12.120"
       *     ]
       */
      okpd2_codes: string[];
      /**
       * Start Price
       * @description Initial max price, RUB
       */
      start_price: number | null;
      /**
       * Subject
       * @example Поставка картриджей для принтеров HP
       */
      subject: string;
    };
    /**
     * NewSupplier
     * @description A company from the SME registry with no bids in the data.
     */
    NewSupplier: {
      /** Headcount */
      headcount: number | null;
      /** Inn */
      inn: string;
      /**
       * Msp Category
       * @description 1 micro, 2 small, 3 medium
       */
      msp_category: number | null;
      /** Name */
      name: string | null;
      /** Okved Main */
      okved_main: string | null;
      /** Okved Name */
      okved_name: string | null;
      /** Reason */
      reason: string;
      /** Region Code */
      region_code: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER" | "UNKNOWN";
      /** Role Display */
      role_display: string;
      /** Score */
      score: number;
    };
    /** OkpdExperience */
    OkpdExperience: {
      /** N Bids */
      n_bids: number;
      /** N Wins */
      n_wins: number;
      /** Prefix */
      prefix: string;
    };
    /** SearchFilters */
    SearchFilters: {
      /**
       * Min Win Rate
       * @description Zero disables the win-rate filter
       */
      min_win_rate: number;
      /**
       * Only Reliable
       * @description Skip companies that are liquidated, owe taxes or have a revenue below the lot's initial price (open FNS data)
       */
      only_reliable: boolean;
      /** Only Smp */
      only_smp: boolean;
      /** Only Spb Lo */
      only_spb_lo: boolean;
      /**
       * Roles
       * @description Empty list matches all roles
       */
      roles: ("MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER" | "UNKNOWN")[];
    };
    /**
     * SearchRequest
     * @description Either an existing lot (lot_id) or a new one (lot).
     */
    SearchRequest: {
      filters: components["schemas"]["SearchFilters"];
      /** Limit */
      limit: number;
      lot: components["schemas"]["NewLot"] | null;
      /** Lot Id */
      lot_id: number | null;
      /**
       * New Limit
       * @description New suppliers to suggest
       */
      new_limit: number;
    };
    /** SearchResponse */
    SearchResponse: {
      /** Items */
      items: components["schemas"]["SupplierRecommendation"][];
      lot: components["schemas"]["LotCard"];
      /** New Suppliers */
      new_suppliers: components["schemas"]["NewSupplier"][];
      /** Timing Ms */
      timing_ms: number;
      /** Total Candidates */
      total_candidates: number;
    };
    /**
     * SupplierCard
     * @description Everything known about a company: history from the data plus the SME registry.
     */
    SupplierCard: {
      /** Avg Won Price */
      avg_won_price: number | null;
      /** Headcount */
      headcount: number | null;
      /** Inn */
      inn: string;
      /** Is Spb Lo */
      is_spb_lo: boolean | null;
      /** Msp Category */
      msp_category: number | null;
      /** Msp Since */
      msp_since: string | null;
      /** N Bids */
      n_bids: number;
      /** N Customers */
      n_customers: number;
      /** N Wins */
      n_wins: number;
      /** Name */
      name: string | null;
      /** Okved Extra */
      okved_extra: string[];
      /** Okved Main */
      okved_main: string | null;
      /** Okved Name */
      okved_name: string | null;
      /** Recent Lots */
      recent_lots: components["schemas"]["EvidenceLot"][];
      /** Region Code */
      region_code: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER" | "UNKNOWN";
      /** Role Display */
      role_display: string;
      /** Role Reason */
      role_reason: string | null;
      /** Top Okpd2 */
      top_okpd2: components["schemas"]["OkpdExperience"][];
      /** @description None without open FNS data */
      trust: components["schemas"]["CompanyTrust"] | null;
      /** Win Rate */
      win_rate: number | null;
    };
    /** SupplierRecommendation */
    SupplierRecommendation: {
      /** Avg Won Price */
      avg_won_price: number | null;
      explanation: components["schemas"]["Explanation"];
      /** Inn */
      inn: string;
      /**
       * Is Actual Winner
       * @description Won this lot in reality (demo)
       */
      is_actual_winner: boolean;
      /**
       * Is Smp
       * @description In the FNS SME registry
       */
      is_smp: boolean | null;
      /** Is Spb Lo */
      is_spb_lo: boolean;
      /** N Bids */
      n_bids: number;
      /** N Wins */
      n_wins: number;
      /** Name */
      name: string | null;
      /** Rank */
      rank: number;
      /** Region Code */
      region_code: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER" | "UNKNOWN";
      /** Role Display */
      role_display: string;
      /** Role Reason */
      role_reason: string | null;
      /**
       * Score
       * @description Relevance in [0, 1] within this result
       */
      score: number;
      /**
       * Warnings
       * @description Reliability warnings: tax debt, loss, revenue vs. the lot price
       */
      warnings: string[];
      /**
       * Win Rate
       * @description Over contested lots; None if none
       */
      win_rate: number | null;
    };
    /** ValidationErrorResponse */
    ValidationErrorResponse: {
      /** Detail */
      detail: components["schemas"]["ValidationIssue"][];
    };
    /** ValidationIssue */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
    /** XaiFactor */
    XaiFactor: {
      /**
       * Impact
       * @description Contribution to the rank score (SHAP); > 0 pushes up
       */
      impact: number;
      /**
       * Name
       * @description Feature key, e.g. customer_score
       */
      name: string;
      /**
       * Text
       * @description Human-readable reason with the actual value
       */
      text: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  match_csv_batch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_match_csv_batch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsvBatchResponse"];
        };
      };
      /** @description CSV file too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsvBatchErrorResponse"];
        };
      };
      /** @description Invalid CSV or missing upload */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsvBatchErrorResponse"];
        };
      };
      /** @description Matching engine unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsvBatchErrorResponse"];
        };
      };
    };
  };
  simulate_batch: {
    parameters: {
      query?: {
        /** @description Notices of this day; default: the last */
        day?: string | null;
        max_lots?: number;
        /** @description Known suppliers to invite */
        per_lot?: number;
        /** @description New registry companies */
        new_per_lot?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_enrichment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inn: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupplierCard"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  search_lots: {
    parameters: {
      query?: {
        query?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LotListItem"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_lot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LotCard"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  search_suppliers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
}
