/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/batch/simulate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Simulate Batch Recommendations
     * @description Simulate background worker matching suppliers to new procurement notices.
     */
    post: operations["simulate_batch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrichment/{inn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Enrichment
     * @description Detailed company profile: OKVED, Minpromtorg registries, SME (MSP) status.
     */
    get: operations["get_enrichment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lots/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Lots
     * @description Search historical lots and procurement notices for 2024-2025.
     */
    get: operations["search_lots"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lots/{lot_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lot
     * @description Get detailed information for a specific lot.
     */
    get: operations["get_lot"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/suppliers/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Search Suppliers
     * @description Search and rank suppliers matching procurement parameters.
     */
    post: operations["search_suppliers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BatchResponse */
    BatchResponse: {
      /** Matched Lots */
      matched_lots: components["schemas"]["MatchedLot"][];
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Service
       * @constant
       */
      service: "rlthack-recsys-backend";
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** LotBase */
    LotBase: {
      /** Customer Inn */
      customer_inn: string | null;
      /** Customer Kpp */
      customer_kpp: string | null;
      /** Is Smp */
      is_smp: boolean;
      /** Okpd2 Code */
      okpd2_code: string;
      /** Procedure Name */
      procedure_name: string;
      /** Start Price */
      start_price: number;
      /** Subject */
      subject: string;
    };
    /** LotResponse */
    LotResponse: {
      /** Customer Inn */
      customer_inn: string | null;
      /** Customer Kpp */
      customer_kpp: string | null;
      /** Is Smp */
      is_smp: boolean;
      /** Lot Id */
      lot_id: number | null;
      /** Okpd2 Code */
      okpd2_code: string;
      /** Procedure Id */
      procedure_id: number | null;
      /** Procedure Name */
      procedure_name: string;
      /** Publish Date */
      publish_date: string | null;
      /** Start Price */
      start_price: number;
      /** Subject */
      subject: string;
    };
    /** MatchedLot */
    MatchedLot: {
      lot: components["schemas"]["LotResponse"];
      recommendations: components["schemas"]["SupplierSearchResponse"];
    };
    /** SupplierEnrichment */
    SupplierEnrichment: {
      /** Inn */
      inn: string;
      /** Is Gisp Manufacturer */
      is_gisp_manufacturer: boolean | null;
      /** Okved Main */
      okved_main: string | null;
      /** Role */
      role: ("MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER") | null;
      /** Status */
      status: string | null;
    };
    /** SupplierProfile */
    SupplierProfile: {
      /** Avg Contract Price */
      avg_contract_price: number;
      /** Contracts Count */
      contracts_count: number;
      /** Inn */
      inn: string;
      /** Is Smp */
      is_smp: boolean;
      /** Is Spb Lo */
      is_spb_lo: boolean;
      /** Kpp */
      kpp: string | null;
      /** Name */
      name: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER";
      /** Role Display */
      role_display: string;
      /** Score */
      score: number;
      /** Win Rate */
      win_rate: number;
      xai: components["schemas"]["XaiReport"] | null;
    };
    /** SupplierSearchRequest */
    SupplierSearchRequest: {
      /** Limit */
      limit: number;
      lot: components["schemas"]["LotBase"];
      /**
       * Min Win Rate
       * @description Zero disables the win-rate filter.
       */
      min_win_rate: number;
      /** Only Smp */
      only_smp: boolean;
      /** Only Spb Lo */
      only_spb_lo: boolean;
      /**
       * Role Filter
       * @description Empty list matches all roles.
       */
      role_filter: ("MANUFACTURER" | "DISTRIBUTOR" | "SUPPLIER")[];
    };
    /** SupplierSearchResponse */
    SupplierSearchResponse: {
      /** Inference Time Ms */
      inference_time_ms: number;
      /** Items */
      items: components["schemas"]["SupplierProfile"][];
      /** Total */
      total: number;
    };
    /** ValidationErrorResponse */
    ValidationErrorResponse: {
      /** Detail */
      detail: components["schemas"]["ValidationIssue"][];
    };
    /** ValidationIssue */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
    /** XaiFactor */
    XaiFactor: {
      /** Description */
      description: string;
      /** Factor Name */
      factor_name: string;
      /** Shap Value */
      shap_value: number;
    };
    /** XaiReport */
    XaiReport: {
      /** Factors */
      factors: components["schemas"]["XaiFactor"][];
      /**
       * Recommendation Level
       * @enum {string}
       */
      recommendation_level: "HIGH" | "MEDIUM" | "LOW";
      /** Summary */
      summary: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  simulate_batch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_enrichment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inn: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupplierEnrichment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  search_lots: {
    parameters: {
      query?: {
        query?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LotResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  get_lot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lot_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
  search_suppliers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierSearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupplierSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
    };
  };
}
